### ISSUE TITLE
Sisow bug `CheckMerchantRequest` response does not include all active payment methods

### ISSUE THREAD

**Issue by rvdsteege** [wp-pay-gateways/sisow#1]
**Question Pronamic** on **29 nov. 2019 14:18**:

> Ik was voor een gebruiker (merchant ID: **********) van onze plugin bezig met iDEAL QR. Het blijkt dat deze betaalmethode niet in de lijst met geactiveerde betaalmethoden (`<payments>`) aanwezig is in de response op een **CheckMerchantRequest**. Klopt dat? Is er een andere manier om te controleren of iDEAL QR gebruikt kan worden?
> 
> Ik zie jullie reactie graag tegemoet.

**Comment by rvdsteege** [comment]
**Jelle Westerhoven** (Sisow) on **29 nov. 2019 15:26**:

> Beste Reüel,
> 
> Bij deze beantwoorden wij graag uw mail.
> 
> iDEAL QR is voor ieder geactiveerd Sisow account al standaard beschikbaar, omdat je hiervoor geen aparte overeenkomst of iets dergelijks voor nodig hebt voor onder andere iDEAL QR.
> 
> Betaalmethoden die op dit moment gebruikt kunnen worden door ieder actief Sisow account zijn:
> 
> - iDEAL (& QR)
> - Bancontact
> - Belfius Pay Button
> - KBC / CBC
> - giropay
> - EPS
> - Overboeking / SEPA credit transfer
> - Bunq
> - Sofort
> 
> Overige betaalmethoden kunnen wel gecontroleerd worden met behulp van de CheckMerchantRequest -methode.
> 
> Met vriendelijke groet,
> 
> Jelle Westerhoven
> Technical Support

**Comment by rvdsteege** [comment]
**Reüel van der Steege** (Pronamic) on **29 nov. 2019 16:15**:

> Beste Jelle,
> 
> Voor wat betreft de betaalmethoden in de **CheckMerchantRequest** response... in de Sisow REST API documentatie (versie 5.3.0) is vermeld:
> 
> > Met de REST methode CheckMerchantRequest kan gecontroleerd worden of de merchant bestaat. Tevens worden de afgenomen betaalmethoden gerapporteerd.
> 
> Maar blijkbaar worden dus niet alle betaalmethoden gerapporteerd, terwijl dat in de voorbeeld response die er bij staat wél het geval is. Daarin zijn bijvoorbeeld _idealqr_ en anderen opgenomen, die in het echt niet in die response aanwezig zijn. Dat is verwarrend.
> 
> Eigenlijk moeten we nu het active element controleren en dan het lijstje dat je stuurde als actief beschouwen. Zou fijn zijn als of de documentatie of de response (dat lijkt mij het meest logische, zodat er geen wijzigingen gemaakt hoeven te worden indien er iets in het 'standaardlijstje' wijzigt) wordt aangepast, zodat met deze request wel alle betaalmethoden kunnen worden opgevraagd. Ik verneem graag van je of we zo'n wijziging kunnen verwachten en of dan de documentatie of de daadwerkelijke respons wordt aangepast, dan kunnen we onze plugin daar op de juiste manier mee laten omgaan.
> 
> Voor de volledigheid: wij gebruiken het opvragen van de betaalmethoden om op basis daarvan de instellingen voor relevante betaalmethoden aan te bieden binnen WordPress. Dus het is wel van belang dat we daar met de juiste betaalmethoden werken :-)
> 
> Met vriendelijke groet,
> 
> Reüel van der Steege
> Pronamic

**Comment by rvdsteege** [comment]
**Mark van Haaren** (Sisow) on **4 dec. 2019 08:46**:

> Beste heer van der Steege,
> 
> Bij deze beantwoord ik graag uw mail.
> 
> Deze betaaloptie zou inderdaad in de CheckMerchantResponse moeten zitten.
> Ik heb gevraagd aan de developers of ze deze kunnen toevoegen.
> 
> Met vriendelijke groet,
> 
> Mark van Haaren
> R&D Manager

**Comment by rvdsteege** [comment]
**Mark van Haaren (Sisow)** on **5 dec. 2019 08:25**:

> Beste Reüel,
> 
> Vanaf vandaag wordt iDEAL QR teruggekoppeld in de API indien actief.
> 
> Met vriendelijke groet,
> 
> Mark van Haaren
> R&D Manager

**Comment by rvdsteege** [comment]
**Reüel van der Steege** (Pronamic) on **6 dec. 2019 09:55**:

> Beste Mark,
> 
> Top, bedankt!
> 
> Ik heb het gecontroleerd en iDEAL QR zit er nu inderdaad bij. De andere actieve betaalmethoden ontbreken helaas nog. Kunnen we die ook nog verwachten?
>
> Met vriendelijke groet,
> 
> Reüel van der Steege
> Pronamic

**Comment by remcotolsma** [comment]
I don't expect this to be relevant any longer now that Sisow has been taken over by Buckaroo. Let's focus on issue https://github.com/pronamic/wp-pronamic-pay-sisow/issues/3 and close this one.
