### ISSUE TITLE
Sisow integration deprecated + switch to Buckaroo integration

### ISSUE THREAD

**Issue by remcotolsma** [wp-pay-gateways/sisow#3]
> # Buckaroo heeft overname Sisow afgerond
>
> _Geplaatst op 30-03-2021_
>
> **Utrecht, 30 maart** - Buckaroo maakt bekend dat de overname van Sisow, een gespecialiseerde payment service provider voor het MKB, is afgerond. Met deze overname levert Buckaroo een betaalplatform waarmee webwinkels, in Nederland en België, verder kunnen groeien.
> 
> Paul Scholten, CEO van Buckaroo: "Wij zijn erg blij met het tempo waarmee de overname is afgerond. Buckaroo levert al 15 jaar betaaloplossingen aan grotere ondernemingen die Europees actief zijn. Hier gaan wij actief mee door. Met de combinatie Sisow en Buckaroo zijn wij ook in staat om onze betaaloplossingen te leveren aan het MKB."
> 
> De overname van Sisow is goedgekeurd door De Nederlandsche Bank. Sisow gaat verder onder de merknaam ‘Sisow by Buckaroo’.  De Sisow-medewerkers gaan mee naar Buckaroo en blijven werkzaam vanuit het kantoor in Helmond.
> 
> ## Betaalstrategie midden- en kleinbedrijf
> 
> "Het jaar 2020 heeft grote veranderingen in het consumentengedrag teweeggebracht en voor 2021 is de verwachting dat de trends die daaruit zijn voortgevloeid, versnellen", aldus Stefan Sprenkels, Head of SME Sisow By Buckaroo. "Veel bedrijven moesten hun bedrijfsmodel aanpassen en verlegden de focus volledig richting online. Het is daarbij belangrijk dat wij het midden- en kleinbedrijf online betaaloplossingen bieden waarmee we verdere groei faciliteren."
> 
> ## Volgende fase
> 
> Ruud Bakens, CEO van Sisow [gaf eerder al](https://www.buckaroo.nl/blog/buckaroo-neemt-betaalaanbieder-sisow-over) te kennen dat Buckaroo en Sisow de juiste ervaring en focus hebben om ‘Sisow by Buckaroo’ te realiseren. Hij ziet dit als de perfecte basis voor een toekomstbestendige positie op de MKB-markt mede gezien de vergelijkbare bedrijfscultuur en complementaire klantbestanden.
> 
> In de laatste tijd is er veelvuldig contact geweest op directie- als op afdelingsniveau van beide ondernemingen en het personeel is alleen nog maar positiever geworden en kijkt uit naar de verdere gezamenlijke samenwerking.

https://www.buckaroo.nl/blog/buckaroo-heeft-overname-sisow-afgerond

---

> Goedemiddag,
> 
> Bedankt voor uw bericht.
> Bij de migratie naar Buckaroo zijn alle actieve live merchants gemigreerd naar het Buckaroo platform.
> Helaas zijn hierbij de test accounts niet gemigreerd.
> Via de onderstaande link kunt u een nieuwe test account aanvragen.
> 
> https://www.buckaroo.nl/start
> 
> Mochten er onduidelijkheden zijn, dan horen wij het graag."
> 
> Met vriendelijke groet/Kind regards,
> 
> Sander van der Hulst
> 
> Buckaroo Client Integration & Support

---

> Beste Remco,
> 
> Bedankt voor uw bericht.
> Wij hebben het onderstaande bericht op 15 juli 2022 om 10:53 uur verstuurd.
> 
> "De Sisow API blijft beschikbaar en klanten zullen niet geforceerd worden om gebruik te maken van de Buckaroo API.
> Met een Buckaroo account is het zowel mogelijk om van de Buckaroo API als Sisow API gebruik te maken.
> Wat voorheen het Merchant ID was bij Sisow is hetzelfde als de Website Key bij Buckaroo (Mijn Buckaroo->Websites->Key).
> En wat voorheen de Merchant Key was bij Sisow is hetzelfde als de Secret Key bij Buckaroo (Configuratie->Beveiliging->Secret Key).
> 
> Mochten er onduidelijkheden zijn, dan horen wij het graag."
> 
> Met vriendelijke groet/Kind regards,
> 
> Sander van der Hulst
> 
> Buckaroo Client Integration & Support

_Internal HelpScout ticket:_ https://secure.helpscout.net/conversation/1945629093/24198/

**Comment by remcotolsma** [comment]
I just tested this with Sisow settings from a customer and it seems that the Sisow settings also works with the [Buckaroo integration](https://github.com/pronamic/wp-pronamic-pay-buckaroo). This means that we can deprecate this Sisow integration and switch customers automatically to the Buckaroo integration. 🎉 This can be done in a similar way as we did for https://github.com/wp-pay-gateways/targetpay and https://github.com/pronamic/wp-pronamic-pay-digiwallet.

**Comment by remcotolsma** [comment]
A point of attention is perhaps the `reservation_payments` support within this integration, but the use is probably so minimal that we do not have to take this into account.

https://github.com/pronamic/wp-pronamic-pay-sisow/blob/3580ea7344259ae5f588f8d5947e2854237dd90e/src/Gateway.php#L63-L67

https://github.com/pronamic/wp-pronamic-pay-sisow/blob/3580ea7344259ae5f588f8d5947e2854237dd90e/src/Gateway.php#L489-L563

**Comment by rvdsteege** [comment]
@remcotolsma I did some updates to use the Buckaroo integration for Sisow configurations. Can you review the changes?

I'm not sure if https://github.com/pronamic/wp-pronamic-pay-buckaroo/commit/96f7ebc94237c5bd72ba090342ca354d2637c978 is really nice to support the Sisow 'Test mode' setting, but I also don't know how to do it otherwise 😉

The Sisow configuration also had an 'Shop ID' setting, but I think it's fine to remove this setting? I don't think there is a Buckaroo replacement.

**Comment by remcotolsma** [comment]
Thanks @rvdsteege i tried to move the commits to a branch:

- https://github.com/pronamic/wp-pronamic-pay-buckaroo/pull/3
- https://github.com/pronamic/wp-pronamic-pay/tree/sisow-buckaroo

Will have a look at it later, will try to focus on following issue for now:

- https://github.com/pronamic/wp-pronamic-pay/issues/154

**Comment by remcotolsma** [comment]
> I'm not sure if https://github.com/pronamic/wp-pronamic-pay-buckaroo/commit/96f7ebc94237c5bd72ba090342ca354d2637c978 is really nice to support the Sisow 'Test mode' setting, but I also don't know how to do it otherwise 😉

Move this to https://github.com/pronamic/wp-pronamic-pay/blob/df5775451e1d6c167496fe59b55a36a62c93f1a4/pronamic-ideal.php#L159-L219 @rvdsteege ?

> The Sisow configuration also had an 'Shop ID' setting, but I think it's fine to remove this setting? I don't think there is a Buckaroo replacement.

👍

We can consider launching Pronamic Pay version `9.0` instead of `8.6`. Pronamic Pay users might pay more attention when updating. And we can draw the attention of Sisow customers to the switch to the Buckaroo API in the changelog.

**Comment by rvdsteege** [comment]
> Move this to https://github.com/pronamic/wp-pronamic-pay/blob/df5775451e1d6c167496fe59b55a36a62c93f1a4/pronamic-ideal.php#L159-L219 @rvdsteege ?

➡️ https://github.com/pronamic/wp-pronamic-pay/commit/e214edc78d57a2c3d03e860cf5593bc7d2fa5638

Also made some changes for this in https://github.com/pronamic/wp-pronamic-pay-buckaroo/pull/3/commits/da24df9c3ab91902a14faea4ff100fcd89594ce0
